services:
  - type: web
    name: exam-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn exam_management_system.wsgi:application
    envVars:
      - key: DEBUG
        value: true
    migrationsCommand: |
      python manage.py makemigrations
      python manage.py migrate
