services:
  - type: web
    name: exam-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn exam_management_system.wsgi:application
    staticPublishPath: staticfiles
    envVars:
      - key: DEBUG
        value: false
    migrationsCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
